document:
  name: Specifiche_Attuative_Pagamenti_1_3_1
  description: |
    Le presenti Specifiche attuative rappresentano l’Allegato A alle citate Linee guida e devono essere 
    utilizzate in combinazione con quest’ultime, nonché con il documento “Specifiche attuative del Nodo 
    dei Pagamenti-SPC” (Allegato B), documenti ai quali si rimanda per tutte le voci e gli argomenti 
    qui non specificatamente indicati.  
  tags:
    - SANP
    - pagoPA
    - SACI
    - AgID
