document:
  name: pagoPA, Codici Identificativi di Versamento, Riversamento e Rendicondazione
  description: |
    Specifiche Attuative dei Codici Identificativi di Versamento, Riversamento e Rendicondazione di pagoPA versione 1.3.1  
  tags:
    - SANP
    - pagoPA
    - SACI
    - AgID
